GET http://localhost:3001/api/slots/reels
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMjMiLCJpZCI6IjY0NTBkMTc5MWQzNDY2YmU1MmIwZmY3MiIsImlhdCI6MTY4MzA2MzI4Nn0.LmopE_1fyBOOVg8VZpCMv5k5uwRWKbP0jQKVzmBV9K0
